//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personal_page_info
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string Id { get; set; }
        public string Password { get; set; }
        public byte[] Avatar { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public string Facebook { get; set; }
        public string Line { get; set; }
        public string Youtube { get; set; }
        public int code { get; set; }
        public string Email { get; set; }
        public Nullable<short> Paid { get; set; }
    }
}
